spring.application.name=rezervasyon

# PostgreSQL Docker Connection
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/ofis_rezervasyon}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:mysecretpassword}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=${JWT_SECRET: insert_your_super_long_and_super_secret_b64_key_here}
jwt.expiration.minutes=${JWT_EXPIRATION_MINUTES:60}

# Frontend URL Configuration
frontend.url=${FRONTEND_URL:http://localhost:5173}

# Scheduling Configuration
app.scheduling.reservation-completion-cron=0 0 0 * * ?
